### ISSUE TITLE
faulty input can cause an endless loop when calculating pH

### ISSUE THREAD

**Issue by jpmattern** [BRCScienceProducts/ESPER#2]
I recently tried to get pH estimates for a million temperature and salinity values, and the computation seemed to take very long. I cancelled the script after a weekend had passed and performed a quick investigation. The problem was caused by a single bad value in the input, a salinity value of 0. With suitable coordinate inputs, the zero can create an infinite loop in `CalculatepHfromTATC`.

Here is a minimum working example that will not terminate:
```
ESPER_LIR(3, [-110, 30, 70; -110, 30, 70], [30, 10; 0, 10], [1, 2], 'Equations', 8, 'EstDates', [2001; 2001]);
```
After adding some debug output, it becomes clear that the iterative procedure to compute pH got lost:
```
iteration 1001, problem index:
     2

deltapH at index:
   -0.9675

pHx at index:
    4.0720
```

I realize that the issue is caused by the bad input (and I'll investigate where that zero came from). But I would suggest adding an iteration counter and trigger a "maximum number of iterations exceeded" error after a threshold has been reached, so that users are not just waiting for ESPER to finish.

**Comment by BRCScienceProducts** [comment]
Indeed, this is an issue that I've encountered with CO2SYS before with low salinity values.  I don't want to alter CO2SYS to ensure it's consistent with the published version, but I'm looking into updating with a warning for these instances.  It should be in the next update.  Thanks again for the report!

**Comment by BRCScienceProducts** [comment]
I just added some error handling to ESPER_NN and ESPER_LIR, and put an iteration limit into the modified CO2sys version called by ESPER.  Hopefully this resolves the issue.  Thank you again for the report!

**Comment by jpmattern** [comment]
I think that is a very useful addition, even if it is just to prevent new users like me from patiently waiting for a solution for more than a day. Thank you!
